name: Feature Request
description: Request a new feature for the Unlocker
title: "[Feature-Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Make sure you fill in every section correctly and with as much detail as possible.
  - type: dropdown
    id: ToolSection
    attributes:
      label: Tool Section
      description: What section of the tool does the feature request impact
      options:
        - Unlocker
        - Spoofer
        - Stats Editor
        - New/Other
    validations:
      required: true
  - type: textarea
    id: Feature-description
    attributes:
      label: What feature are you requesting?
      description: How would you like it to work and what would you want it to do?
    validations:
      required: true
