name: Build and Upload Artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0' # or the appropriate version for your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BuildArtifacts
          path: D:\a\Xbox-Achievement-Unlocker\Xbox-Achievement-Unlocker\bin\Release\net6.0-windows\

