name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1' # or the appropriate version for your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BuildArtifacts
          path: ./path/to/build/directory
